languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "《香蕉鱼鱼文本》"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "大海深处。"

[author]
  name = "Bananafish"
  image = "img/blowfish_logo.png"
  headline = "是谁呢。"
  bio = "我是谁。"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]